In [1]:
!pip install kaggle


In [2]:
import os
import shutil

# Create .kaggle folder
os.makedirs("/root/.kaggle", exist_ok=True)

# Move kaggle.json to the folder
shutil.move("kaggle.json", "/root/.kaggle/kaggle.json")

# Set permissions
os.chmod("/root/.kaggle/kaggle.json", 0o600)


In [3]:
import subprocess

subprocess.run([
    'kaggle', 'datasets', 'download',
    '-d', 'saurabhshahane/twitter-sentiment-dataset',
    '-p', 'D:/mkaggle/twitter-sentiment'
])


CompletedProcess(args=['kaggle', 'datasets', 'download', '-d', 'saurabhshahane/twitter-sentiment-dataset', '-p', 'D:/mkaggle/twitter-sentiment'], returncode=0)

In [4]:
import pandas as pd
import zipfile

zip_path = "D:/mkaggle/twitter-sentiment/twitter-sentiment-dataset.zip"
extract_to = "D:/mkaggle/twitter-sentiment/"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)


In [5]:
import os

# List all files in the folder
folder_path = "D:/mkaggle/twitter-sentiment"
files = os.listdir(folder_path)
print(files)


['twitter-sentiment-dataset.zip', 'Twitter_Data.csv']


In [6]:
import pandas as pd

# Adjust the file name to match the extracted data
file_path = "D:/mkaggle/twitter-sentiment/Twitter_Data.csv"
data = pd.read_csv(file_path)

# Preview the first few rows
print(data.head())


                                          clean_text  category
0  when modi promised “minimum government maximum...      -1.0
1  talk all the nonsense and continue all the dra...       0.0
2  what did just say vote for modi  welcome bjp t...       1.0
3  asking his supporters prefix chowkidar their n...       1.0
4  answer who among these the most powerful world...       1.0


**Importing the dependencies**

In [7]:
import pandas as pd
import numpy as np
import re
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [8]:
# data=pd.read_csv("/content/D:/mkaggle/twitter-sentiment/twitter-sentiment-dataset.zip")

In [9]:
data

clean_text  category
0       when modi promised “minimum government maximum...      -1.0
1       talk all the nonsense and continue all the dra...       0.0
2       what did just say vote for modi  welcome bjp t...       1.0
3       asking his supporters prefix chowkidar their n...       1.0
4       answer who among these the most powerful world...       1.0
...                                                   ...       ...
162975  why these 456 crores paid neerav modi not reco...      -1.0
162976  dear rss terrorist payal gawar what about modi...      -1.0
162977  did you cover her interaction forum where she ...       0.0
162978  there big project came into india modi dream p...       0.0
162979  have you ever listen about like gurukul where ...       1.0

[162980 rows x 2 columns]

In [10]:
data.shape

(162980, 2)

In [11]:
# check missing values
data.isnull().sum()

clean_text    4
category      7
dtype: int64

In [12]:
# remove the missing values
data=data.dropna()

In [13]:
# again check misssing values
data.isnull().sum()

clean_text    0
category      0
dtype: int64

In [14]:
# chech the dist for target col
data['category'].value_counts()

category
 1.0    72249
 0.0    55211
-1.0    35509
Name: count, dtype: int64

In [15]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

In [17]:
# apply function for clean_text
stemmer=PorterStemmer()
def clean_data(content):
  content=re.sub('[^a-zA-Z]',' ',content)
  content=content.lower()
  content=content.split()
  content=[stemmer.stem(word) for word in content if word not in stopwords.words('english')]
  content=" ".join(content)
  return content

In [18]:
data['clean_data']=data['clean_text'].apply(clean_data)

C:\Users\HP\AppData\Local\Temp\ipykernel_14988\1540739013.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['clean_data']=data['clean_text'].apply(clean_data)


In [19]:
data.head()

clean_text  category  \
0  when modi promised “minimum government maximum...      -1.0   
1  talk all the nonsense and continue all the dra...       0.0   
2  what did just say vote for modi  welcome bjp t...       1.0   
3  asking his supporters prefix chowkidar their n...       1.0   
4  answer who among these the most powerful world...       1.0   

                                          clean_data  
0  modi promis minimum govern maximum govern expe...  
1               talk nonsens continu drama vote modi  
2  say vote modi welcom bjp told rahul main campa...  
3  ask support prefix chowkidar name modi great s...  
4  answer among power world leader today trump pu...

In [20]:
# sepearte the independent and dependent data
X=data['clean_data']
Y=data['category']

In [21]:
X

0         modi promis minimum govern maximum govern expe...
1                      talk nonsens continu drama vote modi
2         say vote modi welcom bjp told rahul main campa...
3         ask support prefix chowkidar name modi great s...
4         answer among power world leader today trump pu...
                                ...                        
162975    crore paid neerav modi recov congress leader h...
162976    dear rss terrorist payal gawar modi kill plu m...
162977                            cover interact forum left
162978    big project came india modi dream project happ...
162979    ever listen like gurukul disciplin maintain ev...
Name: clean_data, Length: 162969, dtype: object

In [22]:
Y

0        -1.0
1         0.0
2         1.0
3         1.0
4         1.0
         ... 
162975   -1.0
162976   -1.0
162977    0.0
162978    0.0
162979    1.0
Name: category, Length: 162969, dtype: float64

In [23]:
vectorizer=TfidfVectorizer()
x_vec=vectorizer.fit_transform(X)

In [24]:
# Reduce the dimensions (e.g., to 1000 features)
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=1000)
x_vec_reduced = svd.fit_transform(x_vec)

In [25]:
x_vec_reduced

array([[ 0.11470403, -0.04457056, -0.04834267, ...,  0.03187024,
        -0.00522289, -0.00857426],
       [ 0.12158516, -0.12952544,  0.20032532, ...,  0.01315329,
         0.00391307,  0.00291222],
       [ 0.25006939, -0.15579287,  0.13096566, ...,  0.00302441,
        -0.00095794, -0.00871207],
       ...,
       [ 0.01034799,  0.00062138, -0.00254168, ...,  0.0150607 ,
         0.02696043, -0.02321201],
       [ 0.11974373,  0.08377642,  0.04372611, ..., -0.00528932,
         0.00169723, -0.00602701],
       [ 0.10980116, -0.00242926, -0.0551118 , ..., -0.00828677,
        -0.0080416 , -0.01816555]])

In [26]:
pip install imbalanced-learn

Note: you may need to restart the kernel to use updated packages.


In [27]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=42)
x_resampled,y_resampled=smote.fit_resample(x_vec_reduced,Y)


In [28]:
x_resampled

array([[ 1.14704027e-01, -4.45705626e-02, -4.83426725e-02, ...,
         3.18702435e-02, -5.22288745e-03, -8.57426357e-03],
       [ 1.21585163e-01, -1.29525436e-01,  2.00325318e-01, ...,
         1.31532854e-02,  3.91307379e-03,  2.91221822e-03],
       [ 2.50069389e-01, -1.55792868e-01,  1.30965657e-01, ...,
         3.02440705e-03, -9.57941191e-04, -8.71206943e-03],
       ...,
       [ 1.46828095e-01, -6.64299993e-02, -2.05473360e-02, ...,
         1.46927752e-03,  4.73856729e-04,  7.55874044e-04],
       [ 1.43808121e-01, -3.71156939e-02, -4.12264429e-02, ...,
         3.25432653e-03, -1.86640867e-03, -1.47056082e-04],
       [ 7.10061203e-02,  2.06716262e-02, -3.76720354e-03, ...,
         2.18918003e-03, -5.40280157e-04, -8.09881487e-04]])

In [29]:
y_resampled

0        -1.0
1         0.0
2         1.0
3         1.0
4         1.0
         ... 
216742    0.0
216743    0.0
216744    0.0
216745    0.0
216746    0.0
Name: category, Length: 216747, dtype: float64

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x_resampled,y_resampled,test_size=0.2,random_state=42)

In [31]:
print(f"x_train shape:{x_train.shape}")
print(f"y_train shape:{y_train.shape}")
print(f"x_test shape:{x_test.shape}")
print(f"y_test shape:{y_test.shape}")

x_train shape:(173397, 1000)
y_train shape:(173397,)
x_test shape:(43350, 1000)
y_test shape:(43350,)


In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    AdaBoostClassifier)



In [33]:
models={
    "LogisticRegression":LogisticRegression(),
    "KNeighborsClassifier":KNeighborsClassifier(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "RandomForestClassifier":RandomForestClassifier(),
    "GradientBoostingClassifier":GradientBoostingClassifier(),
    "AdaBoostClassifier":AdaBoostClassifier(),


}

In [34]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

def evaluate(y_true, y_pred):
    return (
        accuracy_score(y_true, y_pred),
        precision_score(y_true, y_pred, average='weighted'),
        recall_score(y_true, y_pred, average='weighted'),
        confusion_matrix(y_true, y_pred)
    )


    # return accu,preci,recall,cm

In [35]:
for modelname,model in models.items():
    # model_name=model[modelname]
    model=model.fit(x_train,y_train)

    y_pred_train=model.predict(x_train)
    y_pred_test=model.predict(x_test)


    accu_train,preci_train,recall_train,cm_train=evaluate(y_train,y_pred_train)
    accu_test,preci_test,recall_test,cm_test=evaluate(y_test,y_pred_test)


    print("=================================================")
    print(f"training score for {modelname}")
    print(f"accuracy_score is :{accu_train}")
    print(f"precision_score is :{preci_train}")
    print(f"recall score is :{recall_train}")
    print(f"confusion_matrix is :{cm_train}")


    

    print("=================================================")
    print(f"testing score for {modelname}")
    print(f"accuracy_score is :{accu_test}")
    print(f"precision_score is :{preci_test}")
    print(f"recall score is :{recall_test}")
    print(f"confusion_matrix is :{cm_test}")





    

c:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


training score for LogisticRegression
accuracy_score is :0.7749211347370485
precision_score is :0.7821457539009836
recall score is :0.7749211347370485
confusion_matrix is :[[39959 12005  5633]
 [ 4752 50634  2569]
 [ 5942  8127 43776]]
testing score for LogisticRegression
accuracy_score is :0.7686505190311419
precision_score is :0.7764861270818261
recall score is :0.7686505190311419
confusion_matrix is :[[10099  3103  1450]
 [ 1187 12449   658]
 [ 1567  2064 10773]]
training score for KNeighborsClassifier
accuracy_score is :0.6695675242362902
precision_score is :0.7579531323179604
recall score is :0.6695675242362902
confusion_matrix is :[[47052 10281   264]
 [ 4077 53557   321]
 [12608 29745 15492]]
testing score for KNeighborsClassifier
accuracy_score is :0.5973702422145328
precision_score is :0.70389499692727
recall score is :0.5973702422145328
confusion_matrix is :[[10523  4028   101]
 [ 1571 12586   137]
 [ 3269  8348  2787]]
training score for DecisionTreeClassifier
accuracy_score

KeyboardInterrupt: 

In [36]:
from sklearn.ensemble import RandomForestClassifier
random=RandomForestClassifier()

In [37]:
from sklearn.model_selection import cross_val_score
 # Cross-validation (optional: cv=5 or another number based on your data)
cv_scores = cross_val_score(random, x_train, y_train, cv=5, scoring='accuracy')
avg_cv_score = cv_scores.mean()


KeyboardInterrupt: 